import next from 'eslint-config-next'

/** @type {import('eslint').Linter.Config[]} */
const eslintConfig = [
  {
    // Global ignores (flat-config: an object with only `ignores` applies repo-wide).
    ignores: [
      '.next/**',
      'node_modules/**',
      'supabase/functions/**', // Deno runtime — different globals/types
      'lib/database.types.ts', // generated by `pnpm db:types`
      'next-env.d.ts',
    ],
  },
  // eslint-config-next 16 ships a native flat config (core-web-vitals + typescript
  // + react-hooks + import + jsx-a11y). Spread it directly — no FlatCompat needed.
  ...next,
  {
    // shadcn/ui primitives are vendored, near-verbatim from the generator — don't
    // fight their idioms (empty interfaces, `any` in a couple of Radix wrappers).
    files: ['components/ui/**/*.{ts,tsx}'],
    rules: {
      '@typescript-eslint/no-empty-object-type': 'off',
      '@typescript-eslint/no-explicit-any': 'off',
    },
  },
  {
    // Node scripts (seeds/smokes) run under Node ESM, not the Next bundler.
    files: ['scripts/**/*.mjs'],
    rules: {
      '@typescript-eslint/no-unused-vars': 'off',
    },
  },
  {
    // eslint-plugin-react-hooks v6 (shipped with eslint-config-next 16) enables the
    // React-Compiler rule family as ERRORS. This codebase predates the compiler, so
    // they fire en masse on patterns that are correct today (setState from an async
    // load in an effect, inline wizard sub-components, derived-state-during-render).
    // Keep them as WARNINGS — visible as future-cleanup signal, but they don't block
    // the local gate. The classic `rules-of-hooks` stays an error (bug-catching);
    // `exhaustive-deps` stays the default warning.
    rules: {
      'react-hooks/static-components': 'warn',
      'react-hooks/set-state-in-effect': 'warn',
      'react-hooks/set-state-in-render': 'warn',
      'react-hooks/refs': 'warn',
      'react-hooks/purity': 'warn',
      'react-hooks/immutability': 'warn',
    },
  },
]

export default eslintConfig
